apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--wwwf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--wwwf
    app.kubernetes.io/part-of: test-app-pr-123
  name: test-component--wwwf
  namespace: appstudio-e2e-test
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component--wwwf
status:
  loadBalancer: {}
